// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLMlH2jPiu7IyWWybBlxDi54b_ye2Ew6o',
    appId: '1:714108448982:web:fc06ec81314dfe0f461977',
    messagingSenderId: '714108448982',
    projectId: 'ey-suvidha-ai',
    authDomain: 'ey-suvidha-ai.firebaseapp.com',
    storageBucket: 'ey-suvidha-ai.firebasestorage.app',
    measurementId: 'G-LR40BBQT5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4CdvLwP3qFi16pCY1mhsvXRrYB-DqWI',
    appId: '1:714108448982:android:d37294d35e91a64b461977',
    messagingSenderId: '714108448982',
    projectId: 'ey-suvidha-ai',
    storageBucket: 'ey-suvidha-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANlM53M9e2ylnP3rXLCFGGo4v8Q_F6rlI',
    appId: '1:714108448982:ios:2fababecf87bf6f0461977',
    messagingSenderId: '714108448982',
    projectId: 'ey-suvidha-ai',
    storageBucket: 'ey-suvidha-ai.firebasestorage.app',
    iosBundleId: 'com.example.suvidhaAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANlM53M9e2ylnP3rXLCFGGo4v8Q_F6rlI',
    appId: '1:714108448982:ios:2fababecf87bf6f0461977',
    messagingSenderId: '714108448982',
    projectId: 'ey-suvidha-ai',
    storageBucket: 'ey-suvidha-ai.firebasestorage.app',
    iosBundleId: 'com.example.suvidhaAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLMlH2jPiu7IyWWybBlxDi54b_ye2Ew6o',
    appId: '1:714108448982:web:51ba34b827e39950461977',
    messagingSenderId: '714108448982',
    projectId: 'ey-suvidha-ai',
    authDomain: 'ey-suvidha-ai.firebaseapp.com',
    storageBucket: 'ey-suvidha-ai.firebasestorage.app',
    measurementId: 'G-53T8ERSCPH',
  );
}
